paths:
  data_folder: "data/processed/Revised_Final_Data"

experiment:
  window_sizes: [24, 48, 72]  # Window sizes to test
  offset: 24  # Forecasting offset
  swc_list: ["SWC_20"]  # Soil moisture columns
  station_list: ["Station1"]  # Stations

hyperparameters:
  epochs: 3  # Number of epochs for training
  batch_size: 32  # Batch size for training
